import { StyleSheet } from "react-native";
import {
  buttonDarkPink,
  defaultBackgroundColor,
  grey,
  lightGrey,
} from "../Consts";

const userStyles = StyleSheet.create({
  appContainer: {
    flex: 1,
  },
  mainContainer: {
    flex: 5,
    width: "100%",
    height: "100%",
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: "2%",
  },
  searchContainer: {
    flex: 4.6,
    width: "90%",
    marginHorizontal: "5%",
    marginBottom: "10%",
  },
  textInputUsers: {
    marginHorizontal: "2%",
    marginVertical: "4%",
    borderWidth: 2,
    borderColor: lightGrey,
    borderRadius: 10,
    width: "78%",
    height: "60%",
    paddingVertical: 8,
    paddingHorizontal: 5,
    backgroundColor: "white",
    color: grey,
    fontSize: 18,
  },
  textInputFriends: {
    marginVertical: "6%",
    borderWidth: 2,
    borderColor: lightGrey,
    borderRadius: 10,
    width: "100%",
    height: "7%",
    paddingVertical: 8,
    paddingHorizontal: 5,
    backgroundColor: "white",
    color: grey,
    fontSize: 18,
  },
  usersList: {
    width: "96%",
    height: "90%",
    marginHorizontal: "2%",
    marginBottom: "2%",
    borderRadius: 10,
  },
  usersListItem: {
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
  },
  userDisplay: {
    flexDirection: "row",
    marginVertical: "1.5%",
    marginRight: 10,
    alignItems: "center",
    justifyContent: "space-between",
  },
  userImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    overflow: "hidden",
    margin: 3,
    marginRight: 10,
  },
  modal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  userModalImage: {
    width: 150,
    height: 150,
    borderRadius: 50,
    overflow: "hidden",
    margin: 3,
    marginRight: 10,
  },
  levelContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  iconsContainer: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  acceptButton: {
    borderWidth: 2,
    borderRadius: 20,
    margin: 5,
    borderColor: "#6aa162",
  },
  rejectButton: {
    borderWidth: 2,
    borderRadius: 20,
    margin: 5,
    borderColor: buttonDarkPink,
  },
  halfButton: {
    width: "48%",
    height: "100%",
    backgroundColor: "lightgrey",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    marginLeft: "2%",
  },
  goBackButton: {
    flexDirection: "row",
    alignItems: "center",
    width: "20%",
  },
  button: {
    width: "80%",
    height: "12%",
    backgroundColor: "lightgrey",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  modalDisplay: {
    marginTop: "20%",
    width: "80%",
    height: "45%",
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    alignItems: "center",
  },
  doubleButton: {
    flexDirection: "row",
    backgroundColor: defaultBackgroundColor,
    width: "78%",
    borderRadius: 15,
    height: "60%",
    marginHorizontal: "2%",
    marginVertical: "4%",
  },
});

export default userStyles;
